[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/attendance"
  to = "https://forms.gle/SqyzHvv6hco4XQBc6"
  status = 301
  force = true

[[redirects]]
  from = "/attendance/"
  to = "https://forms.gle/SqyzHvv6hco4XQBc6"
  status = 301
  force = true

[[redirects]]
  from = "/store"
  to = "https://sasc.bigcartel.com"
  status = 301
  force = true

[[redirects]]
  from = "/seagrad26"
  to = "https://docs.google.com/forms/d/e/1FAIpQLScMxGo6OMtJMKGTfqbgGF9nXf2qUy0lWN0sM-O6CP8v-okGbg/viewform"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 